#!/usr/bin/env Rscript
# Run the cross-language parity suite and write tests/CROSS_VALIDATION_RESULTS.md.
#
# This is the report the project uses to claim the port is faithful, so it is
# generated from an actual test run rather than maintained by hand. Run it from the
# project root:
#
#     Rscript dev/run_parity_report.R
#
# Regenerate the Python baselines first if clifpy has been upgraded:
#
#     cd tests/baseline_py && uv run python generate_baselines.py

suppressPackageStartupMessages({
  library(testthat)
  library(devtools)
})

project_root <- normalizePath(".")
if (!file.exists(file.path(project_root, "DESCRIPTION"))) {
  stop("Run this script from the clifR project root.", call. = FALSE)
}

cat("Loading clifR...\n")
devtools::load_all(project_root, quiet = TRUE)

parity_test_files <- sort(list.files(
  file.path(project_root, "tests", "testthat"),
  pattern = "^test-parity-.*\\.R$",
  full.names = TRUE
))

if (length(parity_test_files) == 0) {
  stop("No parity test files found under tests/testthat/", call. = FALSE)
}

cat(sprintf("Running %d parity test files...\n\n", length(parity_test_files)))

test_results <- testthat::test_dir(
  file.path(project_root, "tests", "testthat"),
  filter = "^parity-",
  reporter = testthat::ListReporter$new(),
  stop_on_failure = FALSE,
  stop_on_warning = FALSE
)

results_frame <- as.data.frame(test_results)

# Each row is one test_that() block; roll them up to the component named by the file.
component_from_file <- function(file_name) {
  component <- sub("^test-parity-", "", file_name)
  sub("\\.R$", "", component)
}

results_frame$component <- component_from_file(results_frame$file)

summarise_component <- function(component_rows) {
  n_failed <- sum(component_rows$failed)
  n_errors <- sum(component_rows$error)
  n_skipped <- sum(component_rows$skipped)
  n_passed <- sum(component_rows$passed)

  status <- if (n_errors > 0 || n_failed > 0) {
    "FAIL"
  } else if (n_skipped > 0 && n_passed == 0) {
    "SKIPPED"
  } else if (n_skipped > 0) {
    "PASS (partial)"
  } else {
    "PASS"
  }

  data.frame(
    component = component_rows$component[1],
    status = status,
    tests = nrow(component_rows),
    assertions_passed = n_passed,
    failed = n_failed,
    errors = n_errors,
    skipped = n_skipped,
    stringsAsFactors = FALSE
  )
}

component_summary <- do.call(
  rbind,
  lapply(split(results_frame, results_frame$component), summarise_component)
)
component_summary <- component_summary[order(component_summary$component), ]

# Pull the clifpy version and fixture details straight from the baseline manifest so
# the report always names the reference it was actually compared against.
manifest_path <- file.path(project_root, "tests", "baseline", "_baseline_manifest.json")
baseline_manifest <- if (file.exists(manifest_path)) {
  jsonlite::fromJSON(manifest_path, simplifyVector = FALSE)
} else {
  list(clifpy_version = "unknown", python_version = "unknown", clif_version = "unknown")
}

status_icon <- function(status) {
  switch(status,
    "PASS" = "PASS",
    "PASS (partial)" = "PASS*",
    "SKIPPED" = "skip",
    "FAIL" = "FAIL",
    status
  )
}

report_lines <- c(
  "# Cross-language validation results",
  "",
  "Generated by `Rscript dev/run_parity_report.R`. Do not edit by hand.",
  "",
  sprintf("- Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  sprintf("- Reference: clifpy %s on Python %s",
          baseline_manifest$clifpy_version, baseline_manifest$python_version),
  sprintf("- clifR: %s", as.character(utils::packageVersion("clifR"))),
  sprintf("- Fixture: `tests/fixtures/cohort/` (CLIF %s)", baseline_manifest$clif_version),
  "",
  "## Component status",
  "",
  "| Component | Status | Tests | Assertions passed | Failed | Errors | Skipped |",
  "|---|---|---|---|---|---|---|"
)

for (row_index in seq_len(nrow(component_summary))) {
  component_row <- component_summary[row_index, ]
  report_lines <- c(report_lines, sprintf(
    "| %s | %s | %d | %d | %d | %d | %d |",
    component_row$component,
    status_icon(component_row$status),
    component_row$tests,
    component_row$assertions_passed,
    component_row$failed,
    component_row$errors,
    component_row$skipped
  ))
}

total_failed <- sum(component_summary$failed)
total_errors <- sum(component_summary$errors)
total_skipped <- sum(component_summary$skipped)

report_lines <- c(
  report_lines,
  "",
  "## Overall",
  "",
  sprintf("- Components compared: %d", nrow(component_summary)),
  sprintf("- Assertions passed: %d", sum(component_summary$assertions_passed)),
  sprintf("- Failures: %d", total_failed),
  sprintf("- Errors: %d", total_errors),
  sprintf("- Skipped: %d", total_skipped),
  ""
)

if (total_failed > 0 || total_errors > 0) {
  report_lines <- c(
    report_lines,
    "## Failing tests",
    ""
  )
  failing_rows <- results_frame[results_frame$failed > 0 | results_frame$error > 0, ]
  for (row_index in seq_len(nrow(failing_rows))) {
    report_lines <- c(report_lines, sprintf(
      "- `%s`: %s", failing_rows$file[row_index], failing_rows$test[row_index]
    ))
  }
  report_lines <- c(report_lines, "")
}

report_lines <- c(
  report_lines,
  "## Tolerances",
  "",
  "| Result kind | Tolerance |",
  "|---|---|",
  "| Clinical scores (SOFA components, CCI, Elixhauser) | exact |",
  "| IDs, encounter blocks, categorical values, counts | exact |",
  "| Converted doses, wide dataset values | 1e-12 |",
  "| Derived ratios and aggregate statistics | 1e-6 |",
  "",
  "See `tests/README.md` for how the harness works and `dev/PORTING_CONVENTIONS.md`",
  "for the porting rules that keep the two implementations aligned.",
  ""
)

output_path <- file.path(project_root, "tests", "CROSS_VALIDATION_RESULTS.md")
writeLines(report_lines, output_path)

cat("\n")
print(component_summary, row.names = FALSE)
cat(sprintf("\nReport written to %s\n", output_path))

if (total_failed > 0 || total_errors > 0) {
  quit(status = 1)
}
